// AUTO-GENERATED by scripts/generate-bs-calendar-data.js — do not edit by hand.
// Source: https://cal.mahansigdel.com.np (BS 2080/01 .. 2085/12), verified contiguous.

/** First BS year covered by BS_MONTH_DAYS. */
export const BS_DATA_START_YEAR = 2080;

/** Last BS year covered by BS_MONTH_DAYS. */
export const BS_DATA_END_YEAR = 2085;

/** AD date (YYYY-MM-DD) of Baisakh 1, 2080 BS. */
export const BS_EPOCH_AD_ISO = '2023-04-14';

/** Days in each BS month, one row of 12 per year from BS_DATA_START_YEAR. */
export const BS_MONTH_DAYS: number[][] = [
  /* 2080 */ [31, 32, 31, 32, 31, 30, 30, 30, 29, 29, 30, 30],
  /* 2081 */ [31, 32, 31, 32, 31, 30, 30, 30, 29, 30, 29, 31],
  /* 2082 */ [31, 31, 32, 31, 31, 31, 30, 29, 30, 29, 30, 30],
  /* 2083 */ [31, 31, 32, 31, 31, 30, 30, 30, 29, 30, 30, 30],
  /* 2084 */ [31, 31, 32, 31, 31, 30, 30, 30, 29, 30, 30, 30],
  /* 2085 */ [31, 32, 31, 32, 30, 31, 30, 30, 29, 30, 30, 30],
];

/** Total days covered (2192): AD 2023-04-14 onward. */
export const BS_DATA_TOTAL_DAYS = 2192;
